# Generated by Django 2.0.7 on 2018-09-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_nme', models.CharField(max_length=100)),
                ('id_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('reg_number', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
